### ISSUE TITLE
关于数据缓存

### ISSUE THREAD

**Issue by Rickyxrc** [wao3/luogu-stats-card#6]
我看到您使用的无服务器函数提供商是`vercel`,我也正在使用。但是，如何实现缓存数据呢？（我也在写一个类似的项目，因GitHub api限制被困扰）

**Comment by wao3** [comment]
目前已经没有使用 vercel 了，主要是免费额度超限了，目前使用的是腾讯云的云开发服务，缓存是通过云开发提供的数据库实现的。
关于 vercel 的缓存可以参考 vercel 的官方文档：https://vercel.com/docs/concepts/edge-network/caching
